export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILUR: 'LOGIN_FAILUR',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILUR: 'LOGOUT_FAILUR'
}


export const userConstants = {
        USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
        USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
        USER_REGISTER_FAILUR: 'USER_REGISTER_FAILUR'
}

export const categoryConstants = {
    GET_ALL_CATEGORIES_REQUEST: 'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_SUCCESS: 'GET_ALL_CATEGORIES_SUCCESS',
    GET_ALL_CATEGORIES_FAILUR: 'GET_ALL_CATEGORIES_FAILUR',
    ADD_NEW_CATEGORIES_REQUEST: 'ADD_NEW_CATEGORIES_REQUEST',
    ADD_NEW_CATEGORIES_SUCCESS: 'ADD_NEW_CATEGORIES_SUCCESS',
    ADD_NEW_CATEGORIES_FAILUR: 'ADD_NEW_CATEGORIES_FAILUR',
    UPDATE_CATEGORIES_REQUEST: 'UPDATE_CATEGORIES_REQUEST',
    UPDATE_CATEGORIES_SUCCESS: 'UPDATE_CATEGORIES_SUCCESS',
    UPDATE_CATEGORIES_FAILUR: 'UPDATE_CATEGORIES_FAILUR',
    DELETE_CATEGORIES_REQUEST: 'DELETE_CATEGORIES_REQUEST',
    DELETE_CATEGORIES_SUCCESS: 'DELETE_CATEGORIES_SUCCESS',
    DELETE_CATEGORIES_FAILUR: 'DELETE_CATEGORIES_FAILUR',
}

export const productConstants = {
    GET_ALL_PRODUCTS_REQUEST: 'GET_ALL_PRODUCTS_REQUEST',
    GET_ALL_PRODUCTS_SUCCESS: 'GET_ALL_PRODUCTS_SUCCESS',
    GET_ALL_PRODUCTS_FAILUR:  'GET_ALL_PRODUCTS_FAILUR',
    ADD_NEW_PRODUCTS_REQUEST: 'ADD_NEW_PRODUCTS_REQUEST',
    ADD_NEW_PRODUCTS_SUCCESS: 'ADD_NEW_PRODUCTS_SUCCESS',
    ADD_NEW_PRODUCTS_FAILUR:  'ADD_NEW_PRODUCTS_FAILUR'
}


export const initialDataConstants = {
    GET_ALL_INITIAL_DATA_REQUEST: 'GET_ALL_INITIAL_DATA_REQUEST',
    GET_ALL_INITIAL_DATA_SUCCESS: 'GET_ALL_INITIAL_DATA_SUCCESS',
    GET_ALL_INITIAL_DATA_FAILUR: 'GET_ALL_INITIAL_DATA_FAILUR' 
}

export const pageConstants = {
    CREATE_PAGE_REQUEST: "CREATE_PAGE_REQUEST",
    CREATE_PAGE_SUCCESS: "CREATE_PAGE_SUCCESS",
    CREATE_PAGE_FAILURE: "CREATE_PAGE_FAILURE",
  };


  export const orderConstants = {
    GET_CUSTOMER_ORDER_REQUEST: "GET_CUSTOMER_ORDER_REQUEST",
    GET_CUSTOMER_ORDER_SUCCESS: "GET_CUSTOMER_ORDER_SUCCESS",
    GET_CUSTOMER_ORDER_FAILURE: "GET_CUSTOMER_ORDER_FAILURE",
  
    UPDATE_CUSTOMER_ORDER_REQUEST: "UPDATE_CUSTOMER_ORDER_REQUEST",
    UPDATE_CUSTOMER_ORDER_SUCCESS: "UPDATE_CUSTOMER_ORDER_SUCCESS",
    UPDATE_CUSTOMER_ORDER_FAILURE: "UPDATE_CUSTOMER_ORDER_FAILURE",
  };